% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Chapter 5: Linear Regression},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Chapter 5: Linear Regression}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}
  \AttributeTok{file =} \StringTok{"returns.csv"}\NormalTok{,}
  \AttributeTok{sep =} \StringTok{";"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           date closes_alior daily_returns_alior daily_log_returns_alior
## 1   01/01/2023     30.16000                  NA                      NA
## 2   02/01/2023     30.16000            0.000000                0.000000
## 3   03/01/2023     33.37000            0.106432                0.101141
## 4   04/01/2023     35.68000            0.069224                0.066933
## 5   05/01/2023     36.27000            0.016536                0.016401
## 6   06/01/2023     37.34000            0.029501                0.029074
## 7   07/01/2023     37.80000            0.012319                0.012244
## 8   08/01/2023     37.03000           -0.020370               -0.020581
## 9   09/01/2023     36.26000           -0.020794               -0.021013
## 10  10/01/2023     36.87000            0.016823                0.016683
## 11  11/01/2023     36.73000           -0.003797               -0.003804
## 12  12/01/2023     36.59000           -0.003812               -0.003819
## 13  13/01/2023     36.89000            0.008199                0.008166
## 14  14/01/2023     36.70000           -0.005150               -0.005164
## 15  15/01/2023     36.51000           -0.005177               -0.005191
## 16  16/01/2023     35.42000           -0.029855               -0.030310
## 17  17/01/2023     34.56000           -0.024280               -0.024580
## 18  18/01/2023     35.22000            0.019097                0.018917
## 19  19/01/2023     35.24000            0.000568                0.000568
## 20  20/01/2023     35.04000           -0.005675               -0.005692
## 21  21/01/2023     33.46000           -0.045091               -0.046140
## 22  22/01/2023     33.59500            0.004035                0.004027
## 23  23/01/2023     33.73000            0.004018                0.004010
## 24  24/01/2023     33.73000            0.000000                0.000000
## 25  25/01/2023     32.97500           -0.022384               -0.022638
## 26  26/01/2023     32.22000           -0.022896               -0.023162
## 27  27/01/2023     34.07000            0.057418                0.055830
## 28  28/01/2023     34.12000            0.001468                0.001466
## 29  29/01/2023     34.61000            0.014361                0.014259
## 30  30/01/2023     34.94000            0.009535                0.009490
## 31  31/01/2023     33.99000           -0.027189               -0.027566
## 32  01/02/2023     33.98000           -0.000294               -0.000294
## 33  02/02/2023     33.91500           -0.001913               -0.001915
## 34  03/02/2023     33.85000           -0.001917               -0.001918
## 35  04/02/2023     35.23000            0.040768                0.039959
## 36  05/02/2023     34.51000           -0.020437               -0.020649
## 37  06/02/2023     33.79000           -0.020864               -0.021084
## 38  07/02/2023     33.73000           -0.001776               -0.001777
## 39  08/02/2023     34.22000            0.014527                0.014423
## 40  09/02/2023     34.35000            0.003799                0.003792
## 41  10/02/2023     35.47000            0.032606                0.032085
## 42  11/02/2023     34.63000           -0.023682               -0.023967
## 43  12/02/2023     34.30000           -0.009529               -0.009575
## 44  13/02/2023     34.10000           -0.005831               -0.005848
## 45  14/02/2023     33.90000           -0.005865               -0.005882
## 46  15/02/2023     33.47000           -0.012684               -0.012765
## 47  16/02/2023     33.71500            0.007320                0.007293
## 48  17/02/2023     33.96000            0.007267                0.007241
## 49  18/02/2023     34.53000            0.016784                0.016645
## 50  19/02/2023     34.61000            0.002317                0.002314
## 51  20/02/2023     35.30000            0.019936                0.019740
## 52  21/02/2023     34.99000           -0.008782               -0.008821
## 53  22/02/2023     34.42000           -0.016290               -0.016425
## 54  23/02/2023     34.34000           -0.002324               -0.002327
## 55  24/02/2023     34.76500            0.012376                0.012300
## 56  25/02/2023     35.19000            0.012225                0.012151
## 57  26/02/2023     35.66000            0.013356                0.013268
## 58  27/02/2023     35.97500            0.008833                0.008795
## 59  28/02/2023     36.29000            0.008756                0.008718
## 60  01/03/2023     35.64000           -0.017911               -0.018074
## 61  02/03/2023     34.20000           -0.040404               -0.041243
## 62  03/03/2023     33.47000           -0.021345               -0.021576
## 63  04/03/2023     33.92000            0.013445                0.013355
## 64  05/03/2023     32.06000           -0.054835               -0.056396
## 65  06/03/2023     31.87000           -0.005926               -0.005944
## 66  07/03/2023     30.88500           -0.030907               -0.031394
## 67  08/03/2023     29.90000           -0.031893               -0.032412
## 68  09/03/2023     29.49000           -0.013712               -0.013807
## 69  10/03/2023     29.82500            0.011360                0.011296
## 70  11/03/2023     30.16000            0.011232                0.011170
## 71  12/03/2023     29.81000           -0.011605               -0.011673
## 72  13/03/2023     29.96000            0.005032                0.005019
## 73  14/03/2023     29.65000           -0.010347               -0.010401
## 74  15/03/2023     31.03000            0.046543                0.045492
## 75  16/03/2023     32.04000            0.032549                0.032031
## 76  17/03/2023     32.89000            0.026529                0.026184
## 77  18/03/2023     33.21000            0.009729                0.009682
## 78  19/03/2023     33.53000            0.009636                0.009590
## 79  20/03/2023     33.68000            0.004474                0.004464
## 80  21/03/2023     33.92000            0.007126                0.007101
## 81  22/03/2023     34.16000            0.007075                0.007051
## 82  23/03/2023     34.97000            0.023712                0.023435
## 83  24/03/2023     33.85000           -0.032027               -0.032552
## 84  25/03/2023     34.01000            0.004727                0.004716
## 85  26/03/2023     35.69000            0.049397                0.048216
## 86  27/03/2023     36.77000            0.030261                0.029812
## 87  28/03/2023     38.46000            0.045961                0.044936
## 88  29/03/2023     38.83000            0.009620                0.009574
## 89  30/03/2023     39.20000            0.009529                0.009484
## 90  31/03/2023     39.48000            0.007143                0.007117
## 91  01/04/2023     39.40500           -0.001900               -0.001902
## 92  02/04/2023     39.33000           -0.001903               -0.001905
## 93  03/04/2023     39.07000           -0.006611               -0.006633
## 94  04/04/2023     39.19000            0.003071                0.003067
## 95  05/04/2023     39.75000            0.014289                0.014188
## 96  06/04/2023     39.15000           -0.015094               -0.015209
## 97  07/04/2023     38.80000           -0.008940               -0.008980
## 98  08/04/2023     37.90000           -0.023196               -0.023469
## 99  09/04/2023     38.38000            0.012665                0.012585
## 100 10/04/2023     38.86000            0.012507                0.012429
## 101 11/04/2023     37.73000           -0.029079               -0.029510
## 102 12/04/2023     37.48000           -0.006626               -0.006648
## 103 13/04/2023     37.23000           -0.006670               -0.006693
## 104 14/04/2023     36.19000           -0.027934               -0.028332
## 105 15/04/2023     36.79000            0.016579                0.016443
## 106 16/04/2023     36.81000            0.000544                0.000543
## 107 17/04/2023     36.51000           -0.008150               -0.008183
## 108 18/04/2023     37.22000            0.019447                0.019260
## 109 19/04/2023     37.18000           -0.001075               -0.001075
## 110 20/04/2023     37.45500            0.007396                0.007369
## 111 21/04/2023     37.73000            0.007342                0.007315
## 112 22/04/2023     36.70000           -0.027299               -0.027679
## 113 23/04/2023     36.73500            0.000954                0.000953
## 114 24/04/2023     36.77000            0.000953                0.000952
## 115 25/04/2023     36.45000           -0.008703               -0.008741
## 116 26/04/2023     36.86000            0.011248                0.011185
## 117 27/04/2023     37.90000            0.028215                0.027824
## 118 28/04/2023     38.16000            0.006860                0.006837
## 119 29/04/2023     38.45000            0.007600                0.007571
## 120 30/04/2023     37.18000           -0.033030               -0.033588
## 121 01/05/2023     37.51000            0.008876                0.008837
## 122 02/05/2023     37.84000            0.008798                0.008759
## 123 03/05/2023     38.49000            0.017178                0.017032
## 124 04/05/2023     38.19500           -0.007664               -0.007694
## 125 05/05/2023     37.90000           -0.007724               -0.007754
## 126 06/05/2023     36.87000           -0.027177               -0.027553
## 127 07/05/2023     35.14000           -0.046922               -0.048058
## 128 08/05/2023     36.15000            0.028742                0.028337
## 129 09/05/2023     38.67000            0.069710                0.067387
## 130 10/05/2023     38.67000            0.000000                0.000000
## 131 11/05/2023     40.38000            0.044220                0.043271
## 132 12/05/2023     39.79000           -0.014611               -0.014719
## 133 13/05/2023     39.20000           -0.014828               -0.014939
## 134 14/05/2023     39.60000            0.010204                0.010152
## 135 15/05/2023     39.11500           -0.012247               -0.012323
## 136 16/05/2023     38.63000           -0.012399               -0.012477
## 137 17/05/2023     37.73000           -0.023298               -0.023574
## 138 18/05/2023     39.31000            0.041876                0.041023
## 139 19/05/2023     39.51000            0.005088                0.005075
## 140 20/05/2023     39.92000            0.010377                0.010324
## 141 21/05/2023     40.05000            0.003257                0.003251
## 142 22/05/2023     39.87000           -0.004494               -0.004505
## 143 23/05/2023     40.42500            0.013920                0.013824
## 144 24/05/2023     40.98000            0.013729                0.013636
## 145 25/05/2023     40.87000           -0.002684               -0.002688
## 146 26/05/2023     40.12500           -0.018229               -0.018397
## 147 27/05/2023     39.38000           -0.018567               -0.018742
## 148 28/05/2023     41.14000            0.044693                0.043723
## 149 29/05/2023     40.87000           -0.006563               -0.006585
## 150 30/05/2023     41.12000            0.006117                0.006098
## 151 31/05/2023     41.13000            0.000243                0.000243
## 152 01/06/2023     42.04000            0.022125                0.021884
## 153 02/06/2023     42.85500            0.019386                0.019201
## 154 03/06/2023     43.67000            0.019018                0.018839
## 155 04/06/2023     43.03000           -0.014655               -0.014764
## 156 05/06/2023     42.38000           -0.015106               -0.015221
## 157 06/06/2023     41.73000           -0.015337               -0.015456
## 158 07/06/2023     42.35000            0.014857                0.014748
## 159 08/06/2023     42.73500            0.009091                0.009050
## 160 09/06/2023     43.12000            0.009009                0.008969
## 161 10/06/2023     43.99000            0.020176                0.019975
## 162 11/06/2023     44.36000            0.008411                0.008376
## 163 12/06/2023     44.73000            0.008341                0.008306
## 164 13/06/2023     46.77000            0.045607                0.044598
## 165 14/06/2023     47.55000            0.016677                0.016540
## 166 15/06/2023     47.57000            0.000421                0.000421
## 167 16/06/2023     48.18000            0.012823                0.012742
## 168 17/06/2023     49.11000            0.019303                0.019119
## 169 18/06/2023     49.67500            0.011505                0.011439
## 170 19/06/2023     50.24000            0.011374                0.011310
## 171 20/06/2023     49.90000           -0.006768               -0.006791
## 172 21/06/2023     49.42000           -0.009619               -0.009666
## 173 22/06/2023     48.94000           -0.009713               -0.009760
## 174 23/06/2023     50.04000            0.022477                0.022228
## 175 24/06/2023     49.72000           -0.006395               -0.006415
## 176 25/06/2023     49.17000           -0.011062               -0.011124
## 177 26/06/2023     50.59000            0.028879                0.028470
## 178 27/06/2023     50.57000           -0.000395               -0.000395
## 179 28/06/2023     50.45000           -0.002373               -0.002376
## 180 29/06/2023     50.26000           -0.003766               -0.003773
## 181 30/06/2023     50.07000           -0.003780               -0.003788
## 182 01/07/2023     49.98000           -0.001797               -0.001799
## 183 02/07/2023     50.02500            0.000900                0.000900
## 184 03/07/2023     50.07000            0.000900                0.000899
## 185 04/07/2023     51.60000            0.030557                0.030100
## 186 05/07/2023     50.99000           -0.011822               -0.011892
## 187 06/07/2023     48.54000           -0.048049               -0.049241
## 188 07/07/2023     49.53000            0.020396                0.020190
## 189 08/07/2023     51.62000            0.042197                0.041331
## 190 09/07/2023     51.15000           -0.009105               -0.009147
## 191 10/07/2023     50.66000           -0.009580               -0.009626
## 192 11/07/2023     50.17000           -0.009672               -0.009719
## 193 12/07/2023     48.42000           -0.034881               -0.035504
## 194 13/07/2023     47.47000           -0.019620               -0.019815
## 195 14/07/2023     46.52000           -0.020013               -0.020216
## 196 15/07/2023     47.81000            0.027730                0.027352
## 197 16/07/2023     47.84500            0.000732                0.000732
## 198 17/07/2023     47.88000            0.000732                0.000731
## 199 18/07/2023     46.91000           -0.020259               -0.020467
## 200 19/07/2023     46.52000           -0.008314               -0.008349
## 201 20/07/2023     46.44500           -0.001612               -0.001614
## 202 21/07/2023     46.37000           -0.001615               -0.001616
## 203 22/07/2023     45.57000           -0.017253               -0.017403
## 204 23/07/2023     47.55000            0.043450                0.042532
## 205 24/07/2023     48.40000            0.017876                0.017718
## 206 25/07/2023     48.75500            0.007335                0.007308
## 207 26/07/2023     49.11000            0.007281                0.007255
## 208 27/07/2023     48.84000           -0.005498               -0.005513
## 209 28/07/2023     48.56000           -0.005733               -0.005750
## 210 29/07/2023     48.28000           -0.005766               -0.005783
## 211 30/07/2023     46.94000           -0.027755               -0.028147
## 212 31/07/2023     46.94000            0.000000                0.000000
## 213 01/08/2023     44.68000           -0.048147               -0.049344
## 214 02/08/2023     42.63000           -0.045882               -0.046968
## 215 03/08/2023     43.21000            0.013605                0.013514
## 216 04/08/2023     43.27000            0.001389                0.001388
## 217 05/08/2023     43.46500            0.004507                0.004496
## 218 06/08/2023     43.66000            0.004486                0.004476
## 219 07/08/2023     44.33000            0.015346                0.015229
## 220 08/08/2023     44.68000            0.007895                0.007864
## 221 09/08/2023     45.03000            0.007833                0.007803
## 222 10/08/2023     44.91000           -0.002665               -0.002668
## 223 11/08/2023     43.35000           -0.034736               -0.035354
## 224 12/08/2023     43.43000            0.001845                0.001844
## 225 13/08/2023     45.03000            0.036841                0.036178
## 226 14/08/2023     43.92000           -0.024650               -0.024959
## 227 15/08/2023     43.31000           -0.013889               -0.013986
## 228 16/08/2023     43.04000           -0.006234               -0.006254
## 229 17/08/2023     42.77000           -0.006273               -0.006293
## 230 18/08/2023     43.38000            0.014262                0.014162
## 231 19/08/2023     42.79000           -0.013601               -0.013694
## 232 20/08/2023     42.20000           -0.013788               -0.013884
## 233 21/08/2023     43.12000            0.021801                0.021567
## 234 22/08/2023     45.03000            0.044295                0.043342
## 235 23/08/2023     43.76000           -0.028203               -0.028609
## 236 24/08/2023     43.03000           -0.016682               -0.016823
## 237 25/08/2023     45.64000            0.060655                0.058887
## 238 26/08/2023     45.93000            0.006354                0.006334
## 239 27/08/2023     47.19000            0.027433                0.027064
## 240 28/08/2023     48.45000            0.026701                0.026350
## 241 29/08/2023     50.70000            0.046440                0.045394
## 242 30/08/2023     50.72500            0.000493                0.000493
## 243 31/08/2023     50.75000            0.000493                0.000493
## 244 01/09/2023     52.73000            0.039015                0.038273
## 245 02/09/2023     52.02000           -0.013465               -0.013556
## 246 03/09/2023     52.68000            0.012687                0.012608
## 247 04/09/2023     54.33000            0.031321                0.030841
## 248 05/09/2023     54.94000            0.011228                0.011165
## 249 06/09/2023     54.16000           -0.014197               -0.014299
## 250 07/09/2023     54.03000           -0.002400               -0.002403
## 251 08/09/2023     53.90000           -0.002406               -0.002409
## 252 09/09/2023     53.79000           -0.002041               -0.002043
## 253 10/09/2023     53.73000           -0.001115               -0.001116
## 254 11/09/2023     53.67000           -0.001117               -0.001117
## 255 12/09/2023     55.63000            0.036519                0.035868
## 256 13/09/2023     56.33000            0.012583                0.012505
## 257 14/09/2023     57.37000            0.018463                0.018294
## 258 15/09/2023     56.59000           -0.013596               -0.013689
## 259 16/09/2023     56.93000            0.006008                0.005990
## 260 17/09/2023     57.27000            0.005972                0.005954
## 261 18/09/2023     57.53000            0.004540                0.004530
## 262 19/09/2023     57.51000           -0.000348               -0.000348
## 263 20/09/2023     57.79500            0.004956                0.004943
## 264 21/09/2023     58.08000            0.004931                0.004919
## 265 22/09/2023     59.20000            0.019284                0.019100
## 266 23/09/2023     59.37500            0.002956                0.002952
## 267 24/09/2023     59.55000            0.002947                0.002943
## 268 25/09/2023     59.82000            0.004534                0.004524
## 269 26/09/2023     60.52000            0.011702                0.011634
## 270 27/09/2023     59.41000           -0.018341               -0.018511
## 271 28/09/2023     60.19000            0.013129                0.013044
## 272 29/09/2023     62.54000            0.039043                0.038300
## 273 30/09/2023     62.10000           -0.007035               -0.007060
## 274 01/10/2023     62.26500            0.002657                0.002653
## 275 02/10/2023     62.43000            0.002650                0.002646
## 276 03/10/2023     63.18000            0.012013                0.011942
## 277 04/10/2023     64.24000            0.016777                0.016638
## 278 05/10/2023     65.30000            0.016501                0.016366
## 279 06/10/2023     63.89000           -0.021593               -0.021829
## 280 07/10/2023     64.48000            0.009235                0.009192
## 281 08/10/2023     64.66000            0.002792                0.002788
## 282 09/10/2023     64.64000           -0.000309               -0.000309
## 283 10/10/2023     63.68000           -0.014851               -0.014963
## 284 11/10/2023     66.29000            0.040986                0.040169
## 285 12/10/2023     66.78500            0.007467                0.007439
## 286 13/10/2023     67.28000            0.007412                0.007385
## 287 14/10/2023     67.09000           -0.002824               -0.002828
## 288 15/10/2023     67.88000            0.011775                0.011706
## 289 16/10/2023     68.67000            0.011638                0.011571
## 290 17/10/2023     67.37000           -0.018931               -0.019113
## 291 18/10/2023     66.76000           -0.009054               -0.009096
## 292 19/10/2023     66.85000            0.001348                0.001347
## 293 20/10/2023     66.59000           -0.003889               -0.003897
## 294 21/10/2023     67.11000            0.007809                0.007779
## 295 22/10/2023     66.62000           -0.007301               -0.007328
## 296 23/10/2023     66.24500           -0.005629               -0.005645
## 297 24/10/2023     65.87000           -0.005661               -0.005677
## 298 25/10/2023     65.98000            0.001670                0.001669
## 299 26/10/2023     65.72500           -0.003865               -0.003872
## 300 27/10/2023     65.47000           -0.003880               -0.003887
## 301 28/10/2023     65.27000           -0.003055               -0.003060
## 302 29/10/2023     65.46000            0.002911                0.002907
## 303 30/10/2023     67.98000            0.038497                0.037774
## 304 31/10/2023     66.67000           -0.019270               -0.019458
## 305 01/11/2023     66.33000           -0.005100               -0.005113
## 306 02/11/2023     66.93000            0.009046                0.009005
## 307 03/11/2023     67.17500            0.003661                0.003654
## 308 04/11/2023     67.42000            0.003647                0.003641
## 309 05/11/2023     66.76000           -0.009789               -0.009838
## 310 06/11/2023     66.56000           -0.002996               -0.003000
## 311 07/11/2023     66.36000           -0.003005               -0.003009
## 312 08/11/2023     63.46000           -0.043701               -0.044685
## 313 09/11/2023     64.92000            0.023007                0.022746
## 314 10/11/2023     64.48000           -0.006778               -0.006801
## 315 11/11/2023     64.76000            0.004342                0.004333
## 316 12/11/2023     65.53000            0.011890                0.011820
## 317 13/11/2023     65.23000           -0.004578               -0.004589
## 318 14/11/2023     64.48500           -0.011421               -0.011487
## 319 15/11/2023     63.74000           -0.011553               -0.011620
## 320 16/11/2023     61.21000           -0.039693               -0.040502
## 321 17/11/2023     61.68000            0.007678                0.007649
## 322 18/11/2023     62.15000            0.007620                0.007591
## 323 19/11/2023     61.30000           -0.013677               -0.013771
## 324 20/11/2023     61.28000           -0.000326               -0.000326
## 325 21/11/2023     59.88000           -0.022846               -0.023111
## 326 22/11/2023     61.74000            0.031062                0.030589
## 327 23/11/2023     60.69000           -0.017007               -0.017153
## 328 24/11/2023     61.63000            0.015489                0.015370
## 329 25/11/2023     61.45000           -0.002921               -0.002925
## 330 26/11/2023     61.27000           -0.002929               -0.002934
## 331 27/11/2023     62.21000            0.015342                0.015225
## 332 28/11/2023     62.40000            0.003054                0.003050
## 333 29/11/2023     62.59000            0.003045                0.003040
## 334 30/11/2023     63.20000            0.009746                0.009699
## 335 01/12/2023     62.47000           -0.011551               -0.011618
## 336 02/12/2023     63.61000            0.018249                0.018084
## 337 03/12/2023     65.58000            0.030970                0.030500
## 338 04/12/2023     65.82000            0.003660                0.003653
## 339 05/12/2023     68.26000            0.037071                0.036400
## 340 06/12/2023     67.87500           -0.005640               -0.005656
## 341 07/12/2023     67.49000           -0.005672               -0.005688
## 342 08/12/2023     67.58000            0.001334                0.001333
## 343 09/12/2023     67.77000            0.002811                0.002808
## 344 10/12/2023     67.96000            0.002804                0.002800
## 345 11/12/2023     66.80000           -0.017069               -0.017216
## 346 12/12/2023     66.66000           -0.002096               -0.002098
## 347 13/12/2023     67.54000            0.013201                0.013115
## 348 14/12/2023     67.37000           -0.002517               -0.002520
## 349 15/12/2023     70.36000            0.044382                0.043425
## 350 16/12/2023     70.64000            0.003980                0.003972
## 351 17/12/2023     71.32500            0.009697                0.009650
## 352 18/12/2023     72.01000            0.009604                0.009558
## 353 19/12/2023     71.80000           -0.002916               -0.002921
## 354 20/12/2023     72.77500            0.013579                0.013488
## 355 21/12/2023     73.75000            0.013397                0.013309
## 356 22/12/2023     74.04000            0.003932                0.003924
## 357 23/12/2023     76.06000            0.027283                0.026917
## 358 24/12/2023     76.76000            0.009203                0.009161
## 359 25/12/2023     77.37000            0.007947                0.007915
## 360 26/12/2023     76.22000           -0.014864               -0.014975
## 361 27/12/2023     77.89000            0.021910                0.021674
## 362 28/12/2023     80.62500            0.035114                0.034511
## 363 29/12/2023     83.36000            0.033922                0.033360
## 364 30/12/2023     82.42000           -0.011276               -0.011340
## 365 31/12/2023     81.98000           -0.005339               -0.005353
## 366 01/01/2024     81.54000           -0.005367               -0.005382
## 367 02/01/2024     79.12000           -0.029679               -0.030128
## 368 03/01/2024     77.97000           -0.014535               -0.014642
## 369 04/01/2024     77.62500           -0.004425               -0.004435
## 370 05/01/2024     77.28000           -0.004444               -0.004454
## 371 06/01/2024     78.44000            0.015010                0.014899
## 372 07/01/2024     79.09000            0.008287                0.008252
## 373 08/01/2024     83.26000            0.052725                0.051382
## 374 09/01/2024     83.45000            0.002282                0.002279
## 375 10/01/2024     83.00500           -0.005333               -0.005347
## 376 11/01/2024     82.56000           -0.005361               -0.005376
## 377 12/01/2024     83.92000            0.016473                0.016339
## 378 13/01/2024     83.09500           -0.009831               -0.009879
## 379 14/01/2024     82.27000           -0.009928               -0.009978
## 380 15/01/2024     82.02000           -0.003039               -0.003043
## 381 16/01/2024     80.84000           -0.014387               -0.014491
## 382 17/01/2024     84.22000            0.041811                0.040961
## 383 18/01/2024     82.86000           -0.016148               -0.016280
## 384 19/01/2024     82.81000           -0.000603               -0.000604
## 385 20/01/2024     83.97000            0.014008                0.013911
## 386 21/01/2024     84.06000            0.001072                0.001071
## 387 22/01/2024     84.15000            0.001071                0.001070
## 388 23/01/2024     85.14000            0.011765                0.011696
## 389 24/01/2024     85.38000            0.002819                0.002815
## 390 25/01/2024     85.62000            0.002811                0.002807
## 391 26/01/2024     85.99000            0.004321                0.004312
## 392 27/01/2024     88.80000            0.032678                0.032156
## 393 28/01/2024     91.93000            0.035248                0.034641
## 394 29/01/2024     93.01000            0.011748                0.011680
## 395 30/01/2024     89.58000           -0.036878               -0.037575
## 396 31/01/2024     91.80000            0.024782                0.024480
## 397 01/02/2024     90.08000           -0.018736               -0.018914
## 398 02/02/2024     88.36000           -0.019094               -0.019279
## 399 03/02/2024     87.36000           -0.011317               -0.011382
## 400 04/02/2024     87.60000            0.002747                0.002743
## 401 05/02/2024     87.84000            0.002740                0.002736
## 402 06/02/2024     86.86000           -0.011157               -0.011219
## 403 07/02/2024     88.06000            0.013815                0.013721
## 404 08/02/2024     90.84000            0.031569                0.031081
## 405 09/02/2024     90.32000           -0.005724               -0.005741
## 406 10/02/2024     92.01000            0.018711                0.018538
## 407 11/02/2024     89.40000           -0.028366               -0.028777
## 408 12/02/2024     89.53500            0.001510                0.001509
## 409 13/02/2024     89.67000            0.001508                0.001507
## 410 14/02/2024     88.32000           -0.015055               -0.015170
## 411 15/02/2024     88.40500            0.000962                0.000962
## 412 16/02/2024     88.49000            0.000961                0.000961
## 413 17/02/2024     91.06000            0.029043                0.028629
## 414 18/02/2024     90.23000           -0.009115               -0.009157
## 415 19/02/2024     90.32000            0.000997                0.000997
## 416 20/02/2024     93.36000            0.033658                0.033104
## 417 21/02/2024     90.27000           -0.033098               -0.033658
## 418 22/02/2024     88.45000           -0.020162               -0.020368
## 419 23/02/2024     89.15000            0.007914                0.007883
## 420 24/02/2024     89.85000            0.007852                0.007821
## 421 25/02/2024     85.50000           -0.048414               -0.049625
## 422 26/02/2024     86.59500            0.012807                0.012726
## 423 27/02/2024     87.69000            0.012645                0.012566
## 424 28/02/2024     87.10000           -0.006728               -0.006751
## 425 29/02/2024     87.11701            0.000195                0.000195
## 426 01/03/2024     87.13403            0.000195                0.000195
## 427 02/03/2024     87.15104            0.000195                0.000195
## 428 03/03/2024     87.16805            0.000195                0.000195
## 429 04/03/2024     87.18506            0.000195                0.000195
## 430 05/03/2024     87.20208            0.000195                0.000195
## 431 06/03/2024     87.21909            0.000195                0.000195
## 432 07/03/2024     87.23610            0.000195                0.000195
## 433 08/03/2024     87.25312            0.000195                0.000195
## 434 09/03/2024     87.27013            0.000195                0.000195
## 435 10/03/2024     87.28714            0.000195                0.000195
## 436 11/03/2024     87.30416            0.000195                0.000195
## 437 12/03/2024     87.32117            0.000195                0.000195
## 438 13/03/2024     87.33818            0.000195                0.000195
## 439 14/03/2024     87.35519            0.000195                0.000195
## 440 15/03/2024     87.37221            0.000195                0.000195
## 441 16/03/2024     87.38922            0.000195                0.000195
## 442 17/03/2024     87.40623            0.000195                0.000195
## 443 18/03/2024     87.42325            0.000195                0.000195
## 444 19/03/2024     87.44026            0.000195                0.000195
## 445 20/03/2024     87.45727            0.000195                0.000195
## 446 21/03/2024     87.47429            0.000195                0.000195
## 447 22/03/2024     87.49130            0.000194                0.000194
## 448 23/03/2024     87.50831            0.000194                0.000194
## 449 24/03/2024     87.52532            0.000194                0.000194
## 450 25/03/2024     87.54234            0.000194                0.000194
## 451 26/03/2024     87.55935            0.000194                0.000194
## 452 27/03/2024     87.57636            0.000194                0.000194
## 453 28/03/2024     87.59338            0.000194                0.000194
## 454 29/03/2024     87.61039            0.000194                0.000194
## 455 30/03/2024     87.62740            0.000194                0.000194
## 456 31/03/2024     87.64442            0.000194                0.000194
## 457 01/04/2024     87.66143            0.000194                0.000194
## 458 02/04/2024     87.67844            0.000194                0.000194
## 459 03/04/2024     87.69545            0.000194                0.000194
## 460 04/04/2024     87.71247            0.000194                0.000194
## 461 05/04/2024     87.72948            0.000194                0.000194
## 462 06/04/2024     87.74649            0.000194                0.000194
## 463 07/04/2024     87.76351            0.000194                0.000194
## 464 08/04/2024     87.78052            0.000194                0.000194
## 465 09/04/2024     87.79753            0.000194                0.000194
## 466 10/04/2024     87.81455            0.000194                0.000194
## 467 11/04/2024     87.83156            0.000194                0.000194
## 468 12/04/2024     87.84857            0.000194                0.000194
## 469 13/04/2024     87.86558            0.000194                0.000194
## 470 14/04/2024     87.88260            0.000194                0.000194
## 471 15/04/2024     87.89961            0.000194                0.000194
## 472 16/04/2024     87.91662            0.000194                0.000194
## 473 17/04/2024     87.93364            0.000194                0.000193
## 474 18/04/2024     87.95065            0.000193                0.000193
## 475 19/04/2024     87.96766            0.000193                0.000193
## 476 20/04/2024     87.98468            0.000193                0.000193
## 477 21/04/2024     88.00169            0.000193                0.000193
## 478 22/04/2024     88.01870            0.000193                0.000193
## 479 23/04/2024     88.03571            0.000193                0.000193
## 480 24/04/2024     88.05273            0.000193                0.000193
## 481 25/04/2024     88.06974            0.000193                0.000193
## 482 26/04/2024     88.08675            0.000193                0.000193
## 483 27/04/2024     88.10377            0.000193                0.000193
## 484 28/04/2024     88.12078            0.000193                0.000193
## 485 29/04/2024     88.13779            0.000193                0.000193
## 486 30/04/2024     88.15481            0.000193                0.000193
## 487 01/05/2024     88.17182            0.000193                0.000193
## 488 02/05/2024     88.18883            0.000193                0.000193
## 489 03/05/2024     88.20584            0.000193                0.000193
## 490 04/05/2024     88.22286            0.000193                0.000193
## 491 05/05/2024     88.23987            0.000193                0.000193
## 492 06/05/2024     88.25688            0.000193                0.000193
## 493 07/05/2024     88.27390            0.000193                0.000193
## 494 08/05/2024     88.29091            0.000193                0.000193
## 495 09/05/2024     88.30792            0.000193                0.000193
## 496 10/05/2024     88.32494            0.000193                0.000193
## 497 11/05/2024     88.34195            0.000193                0.000193
## 498 12/05/2024     88.35896            0.000193                0.000193
## 499 13/05/2024     88.37597            0.000193                0.000193
## 500 14/05/2024     88.39299            0.000193                0.000192
## 501 15/05/2024     88.41000            0.000192                0.000192
## 502 16/05/2024     86.74000           -0.018889               -0.019070
## 503 17/05/2024     86.56000           -0.002075               -0.002077
## 504 18/05/2024     86.90333            0.003966                0.003959
## 505 19/05/2024     87.24667            0.003951                0.003943
## 506 20/05/2024     87.59000            0.003935                0.003927
## 507 21/05/2024     86.25000           -0.015299               -0.015417
## 508 22/05/2024     85.30000           -0.011014               -0.011076
## 509 23/05/2024     86.63000            0.015592                0.015472
## 510 24/05/2024     86.38000           -0.002886               -0.002890
## 511 25/05/2024     86.55333            0.002007                0.002005
## 512 26/05/2024     86.72667            0.002003                0.002001
## 513 27/05/2024     86.90000            0.001999                0.001997
## 514 28/05/2024     86.32000           -0.006674               -0.006697
## 515 29/05/2024     84.71000           -0.018652               -0.018828
## 516 30/05/2024     85.81500            0.013045                0.012960
## 517 31/05/2024     86.92000            0.012877                0.012794
## 518 01/06/2024     87.25333            0.003835                0.003828
## 519 02/06/2024     87.58667            0.003820                0.003813
## 520 03/06/2024     87.92000            0.003806                0.003799
## 521 04/06/2024     83.14000           -0.054368               -0.055901
## 522 05/06/2024     84.67000            0.018403                0.018235
## 523 06/06/2024     85.07000            0.004724                0.004713
## 524 07/06/2024     83.58000           -0.017515               -0.017670
## 525 08/06/2024     83.53667           -0.000518               -0.000519
## 526 09/06/2024     83.49333           -0.000519               -0.000519
## 527 10/06/2024     83.45000           -0.000519               -0.000519
## 528 11/06/2024     82.07000           -0.016537               -0.016675
## 529 12/06/2024     85.87000            0.046302                0.045262
## 530 13/06/2024     82.69000           -0.037033               -0.037736
## 531 14/06/2024     82.87000            0.002177                0.002174
## 532 15/06/2024     83.26333            0.004746                0.004735
## 533 16/06/2024     83.65667            0.004724                0.004713
## 534 17/06/2024     84.05000            0.004702                0.004691
## 535 18/06/2024     84.51000            0.005473                0.005458
## 536 19/06/2024     87.65000            0.037155                0.036482
## 537 20/06/2024     86.63000           -0.011637               -0.011705
## 538 21/06/2024     87.56000            0.010735                0.010678
## 539 22/06/2024     87.96000            0.004568                0.004558
## 540 23/06/2024     88.36000            0.004548                0.004537
## 541 24/06/2024     88.76000            0.004527                0.004517
## 542 25/06/2024     90.77000            0.022645                0.022393
## 543 26/06/2024     91.77000            0.011017                0.010957
## 544 27/06/2024     93.68000            0.020813                0.020599
## 545 28/06/2024     93.00000           -0.007259               -0.007285
## 546 29/06/2024     93.39333            0.004229                0.004220
## 547 30/06/2024     93.78667            0.004212                0.004203
## 548 01/07/2024     94.18000            0.004194                0.004185
## 549 02/07/2024     91.73000           -0.026014               -0.026358
## 550 03/07/2024     92.05000            0.003488                0.003482
## 551 04/07/2024     91.91000           -0.001521               -0.001522
## 552 05/07/2024     90.34000           -0.017082               -0.017230
## 553 06/07/2024     90.71333            0.004133                0.004124
## 554 07/07/2024     91.08667            0.004116                0.004107
## 555 08/07/2024     91.46000            0.004099                0.004090
## 556 09/07/2024     91.96000            0.005467                0.005452
## 557 10/07/2024     91.32000           -0.006960               -0.006984
## 558 11/07/2024     92.68000            0.014893                0.014783
## 559 12/07/2024     91.91000           -0.008308               -0.008343
## 560 13/07/2024     91.91000            0.000000                0.000000
## 561 14/07/2024     91.91000            0.000000                0.000000
## 562 15/07/2024     91.91000            0.000000                0.000000
## 563 16/07/2024     87.59000           -0.047003               -0.048143
## 564 17/07/2024     85.50000           -0.023861               -0.024150
## 565 18/07/2024     88.30000            0.032749                0.032224
## 566 19/07/2024     88.18000           -0.001359               -0.001360
## 567 20/07/2024     88.73667            0.006313                0.006293
## 568 21/07/2024     89.29333            0.006273                0.006254
## 569 22/07/2024     89.85000            0.006234                0.006215
## 570 23/07/2024     87.81000           -0.022705               -0.022966
## 571 24/07/2024     88.96000            0.013096                0.013011
## 572 25/07/2024     89.58000            0.006969                0.006945
## 573 26/07/2024     87.36000           -0.024782               -0.025095
## 574 27/07/2024     87.97667            0.007059                0.007034
## 575 28/07/2024     88.59333            0.007009                0.006985
## 576 29/07/2024     89.21000            0.006961                0.006937
## 577 30/07/2024     86.36000           -0.031947               -0.032469
## 578 31/07/2024     86.20000           -0.001853               -0.001854
## 579 01/08/2024     84.45000           -0.020302               -0.020511
## 580 02/08/2024     81.11000           -0.039550               -0.040353
## 581 03/08/2024     80.91000           -0.002466               -0.002469
## 582 04/08/2024     80.71000           -0.002472               -0.002475
## 583 05/08/2024     80.51000           -0.002478               -0.002481
## 584 06/08/2024     79.76000           -0.009316               -0.009359
## 585 07/08/2024     80.14000            0.004764                0.004753
## 586 08/08/2024     80.80000            0.008236                0.008202
## 587 09/08/2024     80.65000           -0.001856               -0.001858
## 588 10/08/2024     81.48000            0.010291                0.010239
## 589 11/08/2024     82.31000            0.010187                0.010135
## 590 12/08/2024     83.14000            0.010084                0.010033
## 591 13/08/2024     89.16000            0.072408                0.069907
## 592 14/08/2024     90.34000            0.013235                0.013148
## 593 15/08/2024     92.62500            0.025293                0.024979
## 594 16/08/2024     94.91000            0.024669                0.024370
## 595 17/08/2024     94.68333           -0.002388               -0.002391
## 596 18/08/2024     94.45667           -0.002394               -0.002397
## 597 19/08/2024     94.23000           -0.002400               -0.002403
## 598 20/08/2024     90.85000           -0.035870               -0.036529
## 599 21/08/2024     91.50000            0.007155                0.007129
## 600 22/08/2024     92.55000            0.011475                0.011410
## 601 23/08/2024     92.68000            0.001405                0.001404
## 602 24/08/2024     92.47000           -0.002266               -0.002268
## 603 25/08/2024     92.26000           -0.002271               -0.002274
## 604 26/08/2024     92.05000           -0.002276               -0.002279
## 605 27/08/2024     91.32000           -0.007930               -0.007962
## 606 28/08/2024     93.32000            0.021901                0.021665
## 607 29/08/2024     93.27000           -0.000536               -0.000536
## 608 30/08/2024     93.14000           -0.001394               -0.001395
## 609 31/08/2024     93.44333            0.003257                0.003251
## 610 01/09/2024     93.74667            0.003246                0.003241
## 611 02/09/2024     94.05000            0.003236                0.003230
## 612 03/09/2024     92.09000           -0.020840               -0.021060
## 613 04/09/2024     92.64000            0.005972                0.005955
## 614 05/09/2024     90.65000           -0.021481               -0.021715
## 615 06/09/2024     85.34000           -0.058577               -0.060363
## 616 07/09/2024     85.72667            0.004531                0.004521
## 617 08/09/2024     86.11333            0.004510                0.004500
## 618 09/09/2024     86.50000            0.004490                0.004480
## 619 10/09/2024     84.52000           -0.022890               -0.023156
## 620 11/09/2024     81.05000           -0.041055               -0.041922
## 621 12/09/2024     82.91000            0.022949                0.022689
## 622 13/09/2024     85.94000            0.036546                0.035894
## 623 14/09/2024     85.44333           -0.005779               -0.005796
## 624 15/09/2024     84.94667           -0.005813               -0.005830
## 625 16/09/2024     84.45000           -0.005847               -0.005864
## 626 17/09/2024     85.41000            0.011368                0.011304
## 627 18/09/2024     84.96000           -0.005269               -0.005283
## 628 19/09/2024     87.23000            0.026718                0.026368
## 629 20/09/2024     84.51000           -0.031182               -0.031678
## 630 21/09/2024     84.12667           -0.004536               -0.004546
## 631 22/09/2024     83.74333           -0.004557               -0.004567
## 632 23/09/2024     83.36000           -0.004577               -0.004588
## 633 24/09/2024     83.98000            0.007438                0.007410
## 634 25/09/2024     84.09000            0.001310                0.001309
## 635 26/09/2024     88.67000            0.054465                0.053034
## 636 27/09/2024     87.61000           -0.011954               -0.012026
## 637 28/09/2024     86.47667           -0.012936               -0.013021
## 638 29/09/2024     85.34333           -0.013106               -0.013192
## 639 30/09/2024     84.21000           -0.013280               -0.013369
## 640 01/10/2024     82.87000           -0.015913               -0.016041
## 641 02/10/2024     82.60000           -0.003258               -0.003263
## 642 03/10/2024     80.09000           -0.030387               -0.030859
## 643 04/10/2024     80.25000            0.001998                0.001996
## 644 05/10/2024     80.22000           -0.000374               -0.000374
## 645 06/10/2024     80.19000           -0.000374               -0.000374
## 646 07/10/2024     80.16000           -0.000374               -0.000374
## 647 08/10/2024     80.25000            0.001123                0.001122
## 648 09/10/2024     84.56000            0.053707                0.052315
## 649 10/10/2024     85.29000            0.008633                0.008596
## 650 11/10/2024     85.94000            0.007621                0.007592
## 651 12/10/2024     86.29667            0.004150                0.004142
## 652 13/10/2024     86.65333            0.004133                0.004125
## 653 14/10/2024     87.01000            0.004116                0.004108
## 654 15/10/2024     86.67000           -0.003908               -0.003915
## 655 16/10/2024     87.70000            0.011884                0.011814
## 656 17/10/2024     85.01000           -0.030673               -0.031153
## 657 18/10/2024     85.87000            0.010116                0.010066
## 658 19/10/2024     85.56667           -0.003532               -0.003539
## 659 20/10/2024     85.26333           -0.003545               -0.003551
## 660 21/10/2024     84.96000           -0.003558               -0.003564
## 661 22/10/2024     82.91000           -0.024129               -0.024425
## 662 23/10/2024     82.98000            0.000844                0.000844
## 663 24/10/2024     81.25000           -0.020848               -0.021069
## 664 25/10/2024     80.54000           -0.008738               -0.008777
## 665 26/10/2024     80.20333           -0.004180               -0.004189
## 666 27/10/2024     79.86667           -0.004198               -0.004206
## 667 28/10/2024     79.53000           -0.004215               -0.004224
## 668 29/10/2024     83.11000            0.045014                0.044031
## 669 30/10/2024     80.82000           -0.027554               -0.027941
## 670 31/10/2024     79.42000           -0.017322               -0.017474
## 671 01/11/2024     80.28750            0.010923                0.010864
## 672 02/11/2024     81.15500            0.010805                0.010747
## 673 03/11/2024     82.02250            0.010689                0.010633
## 674 04/11/2024     82.89000            0.010576                0.010521
## 675 05/11/2024     82.87000           -0.000241               -0.000241
## 676 06/11/2024     81.98000           -0.010740               -0.010798
## 677 07/11/2024     88.19000            0.075750                0.073018
## 678 08/11/2024     87.05000           -0.012927               -0.013011
## 679 09/11/2024     86.77750           -0.003130               -0.003135
## 680 10/11/2024     86.50500           -0.003140               -0.003145
## 681 11/11/2024     86.23250           -0.003150               -0.003155
## 682 12/11/2024     85.96000           -0.003160               -0.003165
## 683 13/11/2024     82.11000           -0.044788               -0.045822
## 684 14/11/2024     81.85000           -0.003166               -0.003172
## 685 15/11/2024     80.45000           -0.017104               -0.017252
## 686 16/11/2024     80.41000           -0.000497               -0.000497
## 687 17/11/2024     80.37000           -0.000497               -0.000498
## 688 18/11/2024     80.33000           -0.000498               -0.000498
## 689 19/11/2024     78.02000           -0.028756               -0.029178
## 690 20/11/2024     79.60000            0.020251                0.020049
## 691 21/11/2024     79.60000            0.000000                0.000000
## 692 22/11/2024     81.96000            0.029648                0.029217
## 693 23/11/2024     82.71667            0.009232                0.009190
## 694 24/11/2024     83.47333            0.009148                0.009106
## 695 25/11/2024     84.23000            0.009065                0.009024
## 696 26/11/2024     81.58000           -0.031461               -0.031967
## 697 27/11/2024     81.71000            0.001594                0.001592
## 698 28/11/2024     83.54000            0.022396                0.022149
## 699 29/11/2024     82.96000           -0.006943               -0.006967
## 700 30/11/2024     83.27667            0.003817                0.003810
## 701 01/12/2024     83.59333            0.003803                0.003795
## 702 02/12/2024     83.91000            0.003788                0.003781
## 703 03/12/2024     82.83000           -0.012871               -0.012954
## 704 04/12/2024     81.94000           -0.010745               -0.010803
## 705 05/12/2024     82.82000            0.010740                0.010682
## 706 06/12/2024     82.02000           -0.009660               -0.009706
## 707 07/12/2024     81.48667           -0.006502               -0.006524
## 708 08/12/2024     80.95333           -0.006545               -0.006567
## 709 09/12/2024     80.42000           -0.006588               -0.006610
## 710 10/12/2024     80.87000            0.005596                0.005580
## 711 11/12/2024     80.83000           -0.000495               -0.000495
## 712 12/12/2024     80.87000            0.000495                0.000495
## 713 13/12/2024     81.58000            0.008780                0.008741
## 714 14/12/2024     82.01000            0.005271                0.005257
## 715 15/12/2024     82.44000            0.005243                0.005230
## 716 16/12/2024     82.87000            0.005216                0.005202
## 717 17/12/2024     79.87000           -0.036201               -0.036873
## 718 18/12/2024     80.87000            0.012520                0.012443
## 719 19/12/2024     80.07000           -0.009892               -0.009942
## 720 20/12/2024     78.73000           -0.016735               -0.016877
## 721 21/12/2024     78.91000            0.002286                0.002284
## 722 22/12/2024     79.09000            0.002281                0.002278
## 723 23/12/2024     79.27000            0.002276                0.002273
## 724 24/12/2024     79.13750           -0.001672               -0.001673
## 725 25/12/2024     79.00500           -0.001674               -0.001676
## 726 26/12/2024     78.87250           -0.001677               -0.001679
## 727 27/12/2024     78.74000           -0.001680               -0.001681
## 728 28/12/2024     78.53667           -0.002582               -0.002586
## 729 29/12/2024     78.33333           -0.002589               -0.002592
## 730 30/12/2024     78.13000           -0.002596               -0.002599
## 731 31/12/2024     78.13000            0.000000                0.000000
##     closes_ing daily_returns_ing daily_log_returns_ing
## 1     137.3500                NA                    NA
## 2     137.3500          0.000000              0.000000
## 3     142.7100          0.039024              0.038282
## 4     148.0600          0.037489              0.036803
## 5     149.2300          0.007902              0.007871
## 6     152.7400          0.023521              0.023248
## 7     151.4100         -0.008708             -0.008746
## 8     150.5700         -0.005548             -0.005563
## 9     149.7300         -0.005579             -0.005594
## 10    152.2400          0.016764              0.016625
## 11    150.9850         -0.008244             -0.008278
## 12    149.7300         -0.008312             -0.008347
## 13    150.4000          0.004475              0.004465
## 14    147.9750         -0.016124             -0.016255
## 15    145.5500         -0.016388             -0.016524
## 16    143.5400         -0.013810             -0.013906
## 17    141.0300         -0.017486             -0.017641
## 18    143.2100          0.015458              0.015339
## 19    147.0600          0.026884              0.026529
## 20    146.0500         -0.006868             -0.006892
## 21    143.8800         -0.014858             -0.014969
## 22    143.4600         -0.002919             -0.002923
## 23    143.0400         -0.002928             -0.002932
## 24    143.7100          0.004684              0.004673
## 25    141.4500         -0.015726             -0.015851
## 26    139.1900         -0.015977             -0.016106
## 27    144.3800          0.037287              0.036609
## 28    144.5500          0.001177              0.001177
## 29    143.5400         -0.006987             -0.007012
## 30    144.5500          0.007036              0.007012
## 31    142.3700         -0.015081             -0.015196
## 32    140.8700         -0.010536             -0.010592
## 33    141.2050          0.002378              0.002375
## 34    141.5400          0.002372              0.002370
## 35    145.3800          0.027130              0.026769
## 36    144.3800         -0.006879             -0.006902
## 37    143.3800         -0.006926             -0.006950
## 38    138.3600         -0.035012             -0.035639
## 39    139.8600          0.010841              0.010783
## 40    140.5300          0.004791              0.004779
## 41    143.8800          0.023838              0.023559
## 42    141.2000         -0.018627             -0.018802
## 43    140.2000         -0.007082             -0.007107
## 44    140.1150         -0.000606             -0.000606
## 45    140.0300         -0.000607             -0.000607
## 46    136.5200         -0.025066             -0.025386
## 47    137.7750          0.009193              0.009151
## 48    139.0300          0.009109              0.009068
## 49    138.8600         -0.001223             -0.001224
## 50    140.7000          0.013251              0.013164
## 51    142.8700          0.015423              0.015305
## 52    144.3800          0.010569              0.010514
## 53    139.5300         -0.033592             -0.034169
## 54    142.3700          0.020354              0.020150
## 55    144.3800          0.014118              0.014019
## 56    146.3900          0.013922              0.013826
## 57    146.3900          0.000000              0.000000
## 58    145.8050         -0.003996             -0.004004
## 59    145.2200         -0.004012             -0.004020
## 60    146.3900          0.008057              0.008024
## 61    143.8800         -0.017146             -0.017295
## 62    137.5200         -0.044204             -0.045210
## 63    138.8600          0.009744              0.009697
## 64    132.5000         -0.045802             -0.046884
## 65    132.0000         -0.003774             -0.003781
## 66    132.5850          0.004432              0.004422
## 67    133.1700          0.004412              0.004403
## 68    132.5000         -0.005031             -0.005044
## 69    133.1700          0.005057              0.005044
## 70    133.8400          0.005031              0.005019
## 71    131.3300         -0.018754             -0.018932
## 72    133.8400          0.019112              0.018932
## 73    132.3300         -0.011282             -0.011346
## 74    134.6800          0.017759              0.017603
## 75    134.3400         -0.002525             -0.002528
## 76    131.8300         -0.018684             -0.018861
## 77    133.5850          0.013313              0.013225
## 78    135.3400          0.013138              0.013052
## 79    137.1900          0.013669              0.013577
## 80    139.2800          0.015234              0.015119
## 81    141.3700          0.015006              0.014894
## 82    140.0300         -0.009479             -0.009524
## 83    138.6900         -0.009569             -0.009615
## 84    136.3500         -0.016872             -0.017016
## 85    142.0400          0.041731              0.040884
## 86    140.0300         -0.014151             -0.014252
## 87    139.3600         -0.004785             -0.004796
## 88    138.6900         -0.004808             -0.004819
## 89    138.0200         -0.004831             -0.004843
## 90    138.8600          0.006086              0.006068
## 91    139.2800          0.003025              0.003020
## 92    139.7000          0.003016              0.003011
## 93    138.5200         -0.008447             -0.008483
## 94    138.3600         -0.001155             -0.001156
## 95    135.8500         -0.018141             -0.018308
## 96    135.8500          0.000000              0.000000
## 97    134.6800         -0.008612             -0.008650
## 98    133.8400         -0.006237             -0.006257
## 99    133.4200         -0.003138             -0.003143
## 100   133.0000         -0.003148             -0.003153
## 101   132.5000         -0.003759             -0.003766
## 102   133.1700          0.005057              0.005044
## 103   133.8400          0.005031              0.005019
## 104   131.0000         -0.021219             -0.021448
## 105   134.1700          0.024198              0.023910
## 106   138.8600          0.034956              0.034359
## 107   144.5500          0.040977              0.040159
## 108   146.3900          0.012729              0.012649
## 109   141.3700         -0.034292             -0.034894
## 110   139.6950         -0.011848             -0.011919
## 111   138.0200         -0.011990             -0.012063
## 112   138.1900          0.001232              0.001231
## 113   138.8600          0.004848              0.004837
## 114   139.5300          0.004825              0.004813
## 115   143.3800          0.027593              0.027219
## 116   141.0300         -0.016390             -0.016526
## 117   143.7100          0.019003              0.018825
## 118   146.8900          0.022128              0.021887
## 119   148.9000          0.013684              0.013591
## 120   142.3700         -0.043855             -0.044846
## 121   142.2850         -0.000597             -0.000597
## 122   142.2000         -0.000597             -0.000598
## 123   142.7100          0.003586              0.003580
## 124   141.6200         -0.007638             -0.007667
## 125   140.5300         -0.007697             -0.007726
## 126   140.7000          0.001210              0.001209
## 127   136.6800         -0.028571             -0.028988
## 128   139.5300          0.020852              0.020637
## 129   143.0400          0.025156              0.024845
## 130   140.8700         -0.015171             -0.015287
## 131   141.3700          0.003549              0.003543
## 132   141.3700          0.000000              0.000000
## 133   141.3700          0.000000              0.000000
## 134   141.0300         -0.002405             -0.002408
## 135   141.4500          0.002978              0.002974
## 136   141.8700          0.002969              0.002965
## 137   138.0200         -0.027138             -0.027513
## 138   141.3700          0.024272              0.023982
## 139   145.3800          0.028365              0.027970
## 140   146.8900          0.010387              0.010333
## 141   151.2400          0.029614              0.029184
## 142   152.7400          0.009918              0.009869
## 143   152.0750         -0.004354             -0.004363
## 144   151.4100         -0.004373             -0.004382
## 145   150.0700         -0.008850             -0.008890
## 146   147.3900         -0.017858             -0.018020
## 147   144.7100         -0.018183             -0.018350
## 148   150.5700          0.040495              0.039696
## 149   148.5600         -0.013349             -0.013439
## 150   147.7300         -0.005587             -0.005603
## 151   152.9100          0.035064              0.034463
## 152   156.7600          0.025178              0.024866
## 153   154.5850         -0.013875             -0.013972
## 154   152.4100         -0.014070             -0.014170
## 155   155.4200          0.019749              0.019557
## 156   155.0850         -0.002155             -0.002158
## 157   154.7500         -0.002160             -0.002162
## 158   153.7500         -0.006462             -0.006483
## 159   153.8300          0.000520              0.000520
## 160   153.9100          0.000520              0.000520
## 161   158.9300          0.032616              0.032096
## 162   159.7700          0.005285              0.005271
## 163   160.6100          0.005258              0.005244
## 164   169.3900          0.054667              0.053225
## 165   165.9600         -0.020249             -0.020457
## 166   168.9700          0.018137              0.017974
## 167   168.9700          0.000000              0.000000
## 168   169.3900          0.002486              0.002483
## 169   168.7650         -0.003690             -0.003697
## 170   168.1400         -0.003703             -0.003710
## 171   168.9700          0.004936              0.004924
## 172   169.1800          0.001243              0.001242
## 173   169.3900          0.001241              0.001241
## 174   167.3000         -0.012338             -0.012415
## 175   168.5500          0.007472              0.007444
## 176   165.9600         -0.015366             -0.015486
## 177   164.7900         -0.007050             -0.007075
## 178   163.1200         -0.010134             -0.010186
## 179   167.1300          0.024583              0.024286
## 180   165.5400         -0.009514             -0.009559
## 181   163.9500         -0.009605             -0.009651
## 182   159.9400         -0.024459             -0.024763
## 183   163.3700          0.021446              0.021219
## 184   166.8000          0.020995              0.020778
## 185   167.3000          0.002998              0.002993
## 186   163.1200         -0.024985             -0.025302
## 187   158.1000         -0.030775             -0.031258
## 188   158.1000          0.000000              0.000000
## 189   159.7700          0.010563              0.010508
## 190   162.4500          0.016774              0.016635
## 191   165.0850          0.016220              0.016090
## 192   167.7200          0.015961              0.015835
## 193   166.4600         -0.007513             -0.007541
## 194   165.2900         -0.007029             -0.007054
## 195   164.1200         -0.007078             -0.007104
## 196   162.6100         -0.009201             -0.009243
## 197   164.9550          0.014421              0.014318
## 198   167.3000          0.014216              0.014116
## 199   161.9500         -0.031978             -0.032501
## 200   157.9300         -0.024822             -0.025136
## 201   158.8500          0.005825              0.005808
## 202   159.7700          0.005792              0.005775
## 203   155.5900         -0.026163             -0.026511
## 204   159.7700          0.026865              0.026511
## 205   161.7800          0.012581              0.012502
## 206   161.6100         -0.001051             -0.001051
## 207   161.4400         -0.001052             -0.001052
## 208   163.6200          0.013503              0.013413
## 209   162.3650         -0.007670             -0.007700
## 210   161.1100         -0.007729             -0.007760
## 211   158.9300         -0.013531             -0.013624
## 212   157.2600         -0.010508             -0.010563
## 213   155.5900         -0.010619             -0.010676
## 214   158.9300          0.021467              0.021240
## 215   163.9500          0.031586              0.031098
## 216   162.6100         -0.008173             -0.008207
## 217   159.9350         -0.016450             -0.016587
## 218   157.2600         -0.016726             -0.016867
## 219   162.2800          0.031922              0.031423
## 220   162.2800          0.000000              0.000000
## 221   162.2800          0.000000              0.000000
## 222   161.1100         -0.007210             -0.007236
## 223   159.7700         -0.008317             -0.008352
## 224   161.2800          0.009451              0.009407
## 225   159.7700         -0.009363             -0.009407
## 226   155.0900         -0.029292             -0.029730
## 227   153.5800         -0.009736             -0.009784
## 228   153.3300         -0.001628             -0.001629
## 229   153.0800         -0.001630             -0.001632
## 230   155.2500          0.014176              0.014076
## 231   152.0750         -0.020451             -0.020663
## 232   148.9000         -0.020878             -0.021099
## 233   148.7300         -0.001142             -0.001142
## 234   150.5700          0.012371              0.012296
## 235   144.7100         -0.038919             -0.039696
## 236   147.2200          0.017345              0.017196
## 237   150.0700          0.019359              0.019174
## 238   148.9000         -0.007796             -0.007827
## 239   149.4850          0.003929              0.003921
## 240   150.0700          0.003913              0.003906
## 241   156.4300          0.042380              0.041507
## 242   157.2650          0.005338              0.005324
## 243   158.1000          0.005310              0.005295
## 244   159.7700          0.010563              0.010508
## 245   160.2700          0.003129              0.003125
## 246   161.7800          0.009422              0.009377
## 247   172.7400          0.067746              0.065550
## 248   175.6600          0.016904              0.016763
## 249   176.9200          0.007173              0.007147
## 250   174.6200         -0.013000             -0.013085
## 251   172.3200         -0.013171             -0.013259
## 252   169.3900         -0.017003             -0.017149
## 253   170.4350          0.006169              0.006150
## 254   171.4800          0.006131              0.006113
## 255   173.9900          0.014637              0.014531
## 256   173.9900          0.000000              0.000000
## 257   175.2500          0.007242              0.007216
## 258   171.4800         -0.021512             -0.021747
## 259   175.0350          0.020731              0.020519
## 260   178.5900          0.020310              0.020107
## 261   182.7700          0.023406              0.023136
## 262   184.0300          0.006894              0.006870
## 263   188.6300          0.024996              0.024689
## 264   193.2300          0.024386              0.024094
## 265   198.6700          0.028153              0.027764
## 266   195.3250         -0.016837             -0.016980
## 267   191.9800         -0.017125             -0.017274
## 268   195.7400          0.019585              0.019396
## 269   200.7600          0.025646              0.025323
## 270   199.0900         -0.008318             -0.008353
## 271   191.1400         -0.039932             -0.040751
## 272   199.0900          0.041593              0.040751
## 273   192.8100         -0.031544             -0.032052
## 274   195.9500          0.016285              0.016154
## 275   199.0900          0.016024              0.015897
## 276   199.9200          0.004169              0.004160
## 277   201.5950          0.008378              0.008343
## 278   203.2700          0.008309              0.008274
## 279   202.0100         -0.006199             -0.006218
## 280   204.9400          0.014504              0.014400
## 281   204.9400          0.000000              0.000000
## 282   204.9400          0.000000              0.000000
## 283   204.1000         -0.004099             -0.004107
## 284   209.1200          0.024596              0.024298
## 285   206.1950         -0.013987             -0.014086
## 286   203.2700         -0.014186             -0.014287
## 287   202.4300         -0.004132             -0.004141
## 288   205.3600          0.014474              0.014370
## 289   208.2900          0.014268              0.014167
## 290   208.2900          0.000000              0.000000
## 291   213.7200          0.026069              0.025735
## 292   220.8300          0.033268              0.032726
## 293   220.0000         -0.003759             -0.003766
## 294   221.6700          0.007591              0.007562
## 295   227.9400          0.028285              0.027893
## 296   224.1800         -0.016496             -0.016633
## 297   220.4200         -0.016772             -0.016914
## 298   222.0900          0.007576              0.007548
## 299   221.6700         -0.001891             -0.001893
## 300   221.2500         -0.001895             -0.001897
## 301   216.2300         -0.022689             -0.022951
## 302   220.8300          0.021274              0.021051
## 303   225.0200          0.018974              0.018796
## 304   221.6700         -0.014888             -0.014999
## 305   218.7400         -0.013218             -0.013306
## 306   218.3300         -0.001874             -0.001876
## 307   219.1650          0.003824              0.003817
## 308   220.0000          0.003810              0.003803
## 309   215.8200         -0.019000             -0.019183
## 310   214.9800         -0.003892             -0.003900
## 311   214.1400         -0.003907             -0.003915
## 312   211.6300         -0.011721             -0.011791
## 313   215.4000          0.017814              0.017657
## 314   215.8200          0.001950              0.001948
## 315   207.4500         -0.038782             -0.039554
## 316   209.9600          0.012099              0.012027
## 317   214.9800          0.023909              0.023628
## 318   216.6550          0.007791              0.007761
## 319   218.3300          0.007731              0.007701
## 320   215.8200         -0.011496             -0.011563
## 321   215.8200          0.000000              0.000000
## 322   215.8200          0.000000              0.000000
## 323   207.8700         -0.036836             -0.037532
## 324   209.1200          0.006013              0.005995
## 325   206.6100         -0.012003             -0.012075
## 326   206.6100          0.000000              0.000000
## 327   209.9600          0.016214              0.016084
## 328   210.8000          0.004001              0.003993
## 329   210.3800         -0.001992             -0.001994
## 330   209.9600         -0.001996             -0.001998
## 331   211.6300          0.007954              0.007922
## 332   214.3500          0.012853              0.012771
## 333   217.0700          0.012690              0.012610
## 334   215.8200         -0.005759             -0.005775
## 335   209.1200         -0.031044             -0.031536
## 336   214.9800          0.028022              0.027637
## 337   210.8000         -0.019444             -0.019635
## 338   238.4000          0.130930              0.123040
## 339   240.9100          0.010529              0.010473
## 340   238.1900         -0.011291             -0.011355
## 341   235.4700         -0.011419             -0.011485
## 342   242.1600          0.028411              0.028015
## 343   239.6550         -0.010344             -0.010398
## 344   237.1500         -0.010453             -0.010508
## 345   228.7800         -0.035294             -0.035932
## 346   230.0400          0.005507              0.005492
## 347   235.0600          0.021822              0.021588
## 348   229.2000         -0.024930             -0.025246
## 349   233.3800          0.018237              0.018073
## 350   232.5500         -0.003556             -0.003563
## 351   234.2200          0.007181              0.007156
## 352   235.8900          0.007130              0.007105
## 353   240.4900          0.019501              0.019313
## 354   242.3750          0.007838              0.007808
## 355   244.2600          0.007777              0.007747
## 356   246.7700          0.010276              0.010223
## 357   247.6000          0.003363              0.003358
## 358   253.0400          0.021971              0.021733
## 359   255.1300          0.008260              0.008226
## 360   259.3100          0.016384              0.016251
## 361   255.9700         -0.012880             -0.012964
## 362   258.8950          0.011427              0.011362
## 363   261.8200          0.011298              0.011235
## 364   260.5700         -0.004774             -0.004786
## 365   257.4300         -0.012051             -0.012124
## 366   254.2900         -0.012197             -0.012272
## 367   253.8800         -0.001612             -0.001614
## 368   254.7100          0.003269              0.003264
## 369   256.3850          0.006576              0.006555
## 370   258.0600          0.006533              0.006512
## 371   257.2200         -0.003255             -0.003260
## 372   262.6600          0.021149              0.020929
## 373   261.8200         -0.003198             -0.003203
## 374   263.5000          0.006417              0.006396
## 375   264.7550          0.004763              0.004752
## 376   266.0100          0.004740              0.004729
## 377   272.2800          0.023571              0.023297
## 378   268.5150         -0.013828             -0.013924
## 379   264.7500         -0.014022             -0.014121
## 380   258.9000         -0.022096             -0.022344
## 381   258.0600         -0.003244             -0.003250
## 382   272.7000          0.056731              0.055180
## 383   269.7700         -0.010744             -0.010803
## 384   270.1900          0.001557              0.001556
## 385   280.2300          0.037159              0.036485
## 386   280.6450          0.001481              0.001480
## 387   281.0600          0.001479              0.001478
## 388   283.9900          0.010425              0.010371
## 389   287.9650          0.013997              0.013900
## 390   291.9400          0.013804              0.013709
## 391   290.6800         -0.004316             -0.004325
## 392   284.4100         -0.021570             -0.021806
## 393   288.5900          0.014697              0.014590
## 394   292.3600          0.013064              0.012979
## 395   289.4300         -0.010022             -0.010072
## 396   292.3600          0.010123              0.010072
## 397   290.8950         -0.005011             -0.005024
## 398   289.4300         -0.005036             -0.005049
## 399   286.9200         -0.008672             -0.008710
## 400   289.0100          0.007284              0.007258
## 401   291.1000          0.007232              0.007206
## 402   277.6800         -0.046101             -0.047197
## 403   279.5300          0.006662              0.006640
## 404   280.4600          0.003327              0.003321
## 405   280.4600          0.000000              0.000000
## 406   286.0100          0.019789              0.019596
## 407   294.3400          0.029125              0.028709
## 408   291.3300         -0.010226             -0.010279
## 409   288.3200         -0.010332             -0.010386
## 410   290.6400          0.008047              0.008014
## 411   289.7150         -0.003183             -0.003188
## 412   288.7900         -0.003193             -0.003198
## 413   295.7300          0.024031              0.023747
## 414   294.3400         -0.004700             -0.004711
## 415   293.4100         -0.003160             -0.003165
## 416   281.8400         -0.039433             -0.040231
## 417   286.0100          0.014796              0.014687
## 418   278.6000         -0.025908             -0.026250
## 419   279.5300          0.003338              0.003333
## 420   280.4600          0.003327              0.003321
## 421   274.9000         -0.019825             -0.020024
## 422   276.2900          0.005056              0.005044
## 423   277.6800          0.005031              0.005018
## 424   273.0500         -0.016674             -0.016814
## 425   273.0681          0.000066              0.000066
## 426   273.0861          0.000066              0.000066
## 427   273.1042          0.000066              0.000066
## 428   273.1222          0.000066              0.000066
## 429   273.1403          0.000066              0.000066
## 430   273.1583          0.000066              0.000066
## 431   273.1764          0.000066              0.000066
## 432   273.1944          0.000066              0.000066
## 433   273.2125          0.000066              0.000066
## 434   273.2305          0.000066              0.000066
## 435   273.2486          0.000066              0.000066
## 436   273.2666          0.000066              0.000066
## 437   273.2847          0.000066              0.000066
## 438   273.3027          0.000066              0.000066
## 439   273.3208          0.000066              0.000066
## 440   273.3388          0.000066              0.000066
## 441   273.3569          0.000066              0.000066
## 442   273.3749          0.000066              0.000066
## 443   273.3930          0.000066              0.000066
## 444   273.4110          0.000066              0.000066
## 445   273.4291          0.000066              0.000066
## 446   273.4471          0.000066              0.000066
## 447   273.4652          0.000066              0.000066
## 448   273.4832          0.000066              0.000066
## 449   273.5013          0.000066              0.000066
## 450   273.5194          0.000066              0.000066
## 451   273.5374          0.000066              0.000066
## 452   273.5555          0.000066              0.000066
## 453   273.5735          0.000066              0.000066
## 454   273.5916          0.000066              0.000066
## 455   273.6096          0.000066              0.000066
## 456   273.6277          0.000066              0.000066
## 457   273.6457          0.000066              0.000066
## 458   273.6638          0.000066              0.000066
## 459   273.6818          0.000066              0.000066
## 460   273.6999          0.000066              0.000066
## 461   273.7179          0.000066              0.000066
## 462   273.7360          0.000066              0.000066
## 463   273.7540          0.000066              0.000066
## 464   273.7721          0.000066              0.000066
## 465   273.7901          0.000066              0.000066
## 466   273.8082          0.000066              0.000066
## 467   273.8262          0.000066              0.000066
## 468   273.8443          0.000066              0.000066
## 469   273.8623          0.000066              0.000066
## 470   273.8804          0.000066              0.000066
## 471   273.8984          0.000066              0.000066
## 472   273.9165          0.000066              0.000066
## 473   273.9345          0.000066              0.000066
## 474   273.9526          0.000066              0.000066
## 475   273.9706          0.000066              0.000066
## 476   273.9887          0.000066              0.000066
## 477   274.0068          0.000066              0.000066
## 478   274.0248          0.000066              0.000066
## 479   274.0429          0.000066              0.000066
## 480   274.0609          0.000066              0.000066
## 481   274.0790          0.000066              0.000066
## 482   274.0970          0.000066              0.000066
## 483   274.1151          0.000066              0.000066
## 484   274.1331          0.000066              0.000066
## 485   274.1512          0.000066              0.000066
## 486   274.1692          0.000066              0.000066
## 487   274.1873          0.000066              0.000066
## 488   274.2053          0.000066              0.000066
## 489   274.2234          0.000066              0.000066
## 490   274.2414          0.000066              0.000066
## 491   274.2595          0.000066              0.000066
## 492   274.2775          0.000066              0.000066
## 493   274.2956          0.000066              0.000066
## 494   274.3136          0.000066              0.000066
## 495   274.3317          0.000066              0.000066
## 496   274.3497          0.000066              0.000066
## 497   274.3678          0.000066              0.000066
## 498   274.3858          0.000066              0.000066
## 499   274.4039          0.000066              0.000066
## 500   274.4219          0.000066              0.000066
## 501   274.4400          0.000066              0.000066
## 502   270.7400         -0.013482             -0.013574
## 503   269.3500         -0.005134             -0.005147
## 504   269.0400         -0.001151             -0.001152
## 505   268.7300         -0.001152             -0.001153
## 506   268.4200         -0.001154             -0.001154
## 507   266.1100         -0.008606             -0.008643
## 508   265.6500         -0.001729             -0.001730
## 509   273.0500          0.027856              0.027475
## 510   270.2700         -0.010181             -0.010233
## 511   272.4300          0.007992              0.007960
## 512   274.5900          0.007929              0.007897
## 513   276.7500          0.007866              0.007835
## 514   273.5100         -0.011707             -0.011776
## 515   277.6800          0.015246              0.015131
## 516   276.2900         -0.005006             -0.005018
## 517   274.9000         -0.005031             -0.005044
## 518   276.2900          0.005056              0.005044
## 519   277.6800          0.005031              0.005018
## 520   279.0700          0.005006              0.004993
## 521   266.5700         -0.044792             -0.045826
## 522   273.5100          0.026034              0.025701
## 523   265.1800         -0.030456             -0.030929
## 524   265.1800          0.000000              0.000000
## 525   265.7967          0.002325              0.002323
## 526   266.4133          0.002320              0.002317
## 527   267.0300          0.002315              0.002312
## 528   259.1700         -0.029435             -0.029877
## 529   263.3300          0.016051              0.015924
## 530   256.8500         -0.024608             -0.024916
## 531   256.8500          0.000000              0.000000
## 532   258.8567          0.007813              0.007782
## 533   260.8633          0.007752              0.007722
## 534   262.8700          0.007692              0.007663
## 535   262.8700          0.000000              0.000000
## 536   267.5000          0.017613              0.017460
## 537   268.8900          0.005196              0.005183
## 538   273.0500          0.015471              0.015353
## 539   273.0500          0.000000              0.000000
## 540   273.0500          0.000000              0.000000
## 541   273.0500          0.000000              0.000000
## 542   277.6800          0.016957              0.016814
## 543   278.6000          0.003313              0.003308
## 544   276.2900         -0.008291             -0.008326
## 545   281.3800          0.018423              0.018255
## 546   282.3067          0.003293              0.003288
## 547   283.2333          0.003282              0.003277
## 548   284.1600          0.003272              0.003266
## 549   276.7500         -0.026077             -0.026423
## 550   273.9800         -0.010009             -0.010059
## 551   277.6800          0.013505              0.013414
## 552   274.9000         -0.010012             -0.010062
## 553   275.5167          0.002243              0.002241
## 554   276.1333          0.002238              0.002236
## 555   276.7500          0.002233              0.002231
## 556   280.4600          0.013406              0.013317
## 557   277.6800         -0.009912             -0.009962
## 558   277.6800          0.000000              0.000000
## 559   279.9900          0.008319              0.008285
## 560   279.0667         -0.003298             -0.003303
## 561   278.1433         -0.003309             -0.003314
## 562   277.2200         -0.003320             -0.003325
## 563   273.0500         -0.015042             -0.015156
## 564   270.2700         -0.010181             -0.010233
## 565   271.6600          0.005143              0.005130
## 566   270.7400         -0.003387             -0.003392
## 567   270.1233         -0.002278             -0.002280
## 568   269.5067         -0.002283             -0.002286
## 569   268.8900         -0.002288             -0.002291
## 570   271.2000          0.008591              0.008554
## 571   269.3500         -0.006822             -0.006845
## 572   271.6600          0.008576              0.008540
## 573   267.9600         -0.013620             -0.013714
## 574   268.5767          0.002301              0.002299
## 575   269.1933          0.002296              0.002293
## 576   269.8100          0.002291              0.002288
## 577   274.9000          0.018865              0.018689
## 578   279.5300          0.016842              0.016702
## 579   265.1800         -0.051336             -0.052701
## 580   256.3900         -0.033147             -0.033709
## 581   252.6867         -0.014444             -0.014549
## 582   248.9833         -0.014656             -0.014764
## 583   245.2800         -0.014874             -0.014986
## 584   242.9700         -0.009418             -0.009462
## 585   238.3400         -0.019056             -0.019240
## 586   241.1200          0.011664              0.011597
## 587   245.2800          0.017253              0.017106
## 588   246.9767          0.006917              0.006893
## 589   248.6733          0.006870              0.006846
## 590   250.3700          0.006823              0.006800
## 591   247.6000         -0.011064             -0.011125
## 592   250.8400          0.013086              0.013001
## 593   254.5400          0.014750              0.014643
## 594   258.2400          0.014536              0.014431
## 595   257.7767         -0.001794             -0.001796
## 596   257.3133         -0.001797             -0.001799
## 597   256.8500         -0.001801             -0.001802
## 598   253.6100         -0.012614             -0.012695
## 599   252.2300         -0.005441             -0.005456
## 600   254.0800          0.007335              0.007308
## 601   252.6900         -0.005471             -0.005486
## 602   251.4567         -0.004881             -0.004893
## 603   250.2233         -0.004905             -0.004917
## 604   248.9900         -0.004929             -0.004941
## 605   250.8400          0.007430              0.007403
## 606   250.3700         -0.001874             -0.001875
## 607   250.3700          0.000000              0.000000
## 608   258.2400          0.031433              0.030950
## 609   257.3133         -0.003588             -0.003595
## 610   256.3867         -0.003601             -0.003608
## 611   255.4600         -0.003614             -0.003621
## 612   251.7600         -0.014484             -0.014590
## 613   253.6100          0.007348              0.007321
## 614   248.9900         -0.018217             -0.018385
## 615   236.9500         -0.048355             -0.049564
## 616   237.4133          0.001955              0.001953
## 617   237.8767          0.001952              0.001950
## 618   238.3400          0.001948              0.001946
## 619   236.0300         -0.009692             -0.009739
## 620   226.7700         -0.039232             -0.040023
## 621   239.2700          0.055122              0.053656
## 622   242.9700          0.015464              0.015345
## 623   242.0433         -0.003814             -0.003821
## 624   241.1167         -0.003829             -0.003836
## 625   240.1900         -0.003843             -0.003851
## 626   242.5100          0.009659              0.009613
## 627   242.5100          0.000000              0.000000
## 628   237.4200         -0.020989             -0.021212
## 629   238.8000          0.005812              0.005796
## 630   238.1833         -0.002582             -0.002586
## 631   237.5667         -0.002589             -0.002592
## 632   236.9500         -0.002596             -0.002599
## 633   243.4300          0.027348              0.026980
## 634   241.1200         -0.009489             -0.009535
## 635   246.6700          0.023018              0.022757
## 636   245.2800         -0.005635             -0.005651
## 637   244.6633         -0.002514             -0.002517
## 638   244.0467         -0.002520             -0.002524
## 639   243.4300         -0.002527             -0.002530
## 640   237.4200         -0.024689             -0.024999
## 641   240.6600          0.013647              0.013554
## 642   236.0300         -0.019239             -0.019426
## 643   236.9500          0.003898              0.003890
## 644   237.4133          0.001955              0.001953
## 645   237.8767          0.001952              0.001950
## 646   238.3400          0.001948              0.001946
## 647   239.7300          0.005832              0.005815
## 648   242.9700          0.013515              0.013425
## 649   242.5100         -0.001893             -0.001895
## 650   247.6000          0.020989              0.020772
## 651   248.5233          0.003729              0.003722
## 652   249.4467          0.003715              0.003708
## 653   250.3700          0.003702              0.003695
## 654   255.9300          0.022207              0.021964
## 655   254.0800         -0.007229             -0.007255
## 656   242.5100         -0.045537             -0.046606
## 657   245.2800          0.011422              0.011357
## 658   246.0533          0.003153              0.003148
## 659   246.8267          0.003143              0.003138
## 660   247.6000          0.003133              0.003128
## 661   238.8000         -0.035541             -0.036188
## 662   240.1900          0.005821              0.005804
## 663   239.7300         -0.001915             -0.001917
## 664   236.4900         -0.013515             -0.013607
## 665   235.8733         -0.002608             -0.002611
## 666   235.2567         -0.002614             -0.002618
## 667   234.6400         -0.002621             -0.002625
## 668   232.3200         -0.009887             -0.009937
## 669   236.0300          0.015969              0.015843
## 670   230.0100         -0.025505             -0.025836
## 671   229.8950         -0.000500             -0.000500
## 672   229.7800         -0.000500             -0.000500
## 673   229.6650         -0.000500             -0.000501
## 674   229.5500         -0.000501             -0.000501
## 675   230.9400          0.006055              0.006037
## 676   228.1600         -0.012038             -0.012111
## 677   236.0300          0.034493              0.033912
## 678   234.6400         -0.005889             -0.005906
## 679   236.0275          0.005913              0.005896
## 680   237.4150          0.005879              0.005861
## 681   238.8025          0.005844              0.005827
## 682   240.1900          0.005810              0.005793
## 683   239.2700         -0.003830             -0.003838
## 684   236.4900         -0.011619             -0.011687
## 685   233.7100         -0.011755             -0.011825
## 686   233.0933         -0.002639             -0.002642
## 687   232.4767         -0.002646             -0.002649
## 688   231.8600         -0.002653             -0.002656
## 689   222.1400         -0.041922             -0.042826
## 690   222.6100          0.002116              0.002114
## 691   226.3100          0.016621              0.016484
## 692   226.7700          0.002033              0.002031
## 693   223.0667         -0.016331             -0.016466
## 694   219.3633         -0.016602             -0.016741
## 695   215.6600         -0.016882             -0.017026
## 696   211.0400         -0.021423             -0.021655
## 697   210.1100         -0.004407             -0.004416
## 698   214.7400          0.022036              0.021797
## 699   218.9000          0.019372              0.019187
## 700   220.2900          0.006350              0.006330
## 701   221.6800          0.006310              0.006290
## 702   223.0700          0.006270              0.006251
## 703   217.5200         -0.024880             -0.025195
## 704   220.2900          0.012734              0.012654
## 705   221.2200          0.004222              0.004213
## 706   230.4700          0.041814              0.040963
## 707   230.7800          0.001345              0.001344
## 708   231.0900          0.001343              0.001342
## 709   231.4000          0.001341              0.001341
## 710   238.3400          0.029991              0.029550
## 711   237.4200         -0.003860             -0.003868
## 712   233.2500         -0.017564             -0.017720
## 713   230.0100         -0.013891             -0.013988
## 714   229.8567         -0.000667             -0.000667
## 715   229.7033         -0.000667             -0.000667
## 716   229.5500         -0.000668             -0.000668
## 717   220.2900         -0.040340             -0.041176
## 718   224.9200          0.021018              0.020800
## 719   224.9200          0.000000              0.000000
## 720   233.7100          0.039081              0.038336
## 721   230.7800         -0.012537             -0.012616
## 722   227.8500         -0.012696             -0.012777
## 723   224.9200         -0.012859             -0.012943
## 724   224.8050         -0.000511             -0.000511
## 725   224.6900         -0.000512             -0.000512
## 726   224.5750         -0.000512             -0.000512
## 727   224.4600         -0.000512             -0.000512
## 728   224.1500         -0.001381             -0.001382
## 729   223.8400         -0.001383             -0.001384
## 730   223.5300         -0.001385             -0.001386
## 731   223.5300          0.000000              0.000000
\end{verbatim}

\subsection{Returns and Log-Returns}\label{returns-and-log-returns}

In financial analysis, \textbf{returns} and \textbf{log-returns} play a
key role in measuring the relative changes in asset prices over time.

\subsubsection{Simple Returns}\label{simple-returns}

A \textbf{simple return} calculates the relative change in price between
consecutive periods:

\[
R_t = \frac{P_t - P_{t-1}}{P_{t-1}}
\]

where \(P_t\) is the price at time \(t\), and \(P_{t-1}\) is the price
in the previous period. Simple returns are intuitive, but they
\textbf{do not add up linearly over time}, which can complicate
multi-period analysis.

\subsubsection{Log-Returns}\label{log-returns}

A \textbf{log-return} is defined as:

\[
r_t = \ln\frac{P_t}{P_{t-1}} = \ln(P_t) - \ln(P_{t-1})
\]

The advantage of log-returns is their \textbf{additivity over time} --
the log-return over multiple periods is the sum of the individual period
log-returns. They are also often more suitable for modeling financial
data, especially when prices grow exponentially.

\subsubsection{Context in the Analyzed
Data}\label{context-in-the-analyzed-data}

In the data from \textbf{09/2023--02/2024}, there was a clear upward
trend in the stock prices of both companies, which often moved
\textbf{in parallel}. Therefore, a natural step is to analyze
\textbf{log-returns}, which better highlight relative price changes and
facilitate further statistical modeling.

Returns and log-returns were calculated in \textbf{Excel} and then
imported into \textbf{R}, where \textbf{histograms} and a
\textbf{scatter plot} comparing the log-returns of both companies were
prepared. These visualizations allow for assessing the data distribution
and the degree of interdependence between the companies.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alior\_log\_returns }\OtherTok{\textless{}{-}}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{daily\_log\_returns\_alior[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{]}
\NormalTok{ing\_log\_returns }\OtherTok{\textless{}{-}}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{daily\_log\_returns\_ing[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# install.packages("ggplot2")}
\CommentTok{\# install.packages("ggExtra")}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(ggExtra)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alior\_ing }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{alior\_log\_returns =}\NormalTok{ alior\_log\_returns,}
  \AttributeTok{ing\_log\_returns   =}\NormalTok{ ing\_log\_returns}
\NormalTok{)}

\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(alior\_ing, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ alior\_log\_returns, }\AttributeTok{y =}\NormalTok{ ing\_log\_returns)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.6}\NormalTok{, }\AttributeTok{color =} \StringTok{"darkblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Alior \& ING Bank Log{-}Returns (2023{-}2024) with Marginals"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Alior Bank"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"ING Bank"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}

\FunctionTok{ggMarginal}\NormalTok{(}
\NormalTok{  p,}
  \AttributeTok{type =} \StringTok{"histogram"}\NormalTok{,}
  \AttributeTok{margins =} \StringTok{"both"}\NormalTok{,}
  \AttributeTok{fill =} \StringTok{"lightblue"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{05_linear_regression_files/figure-latex/unnamed-chunk-5-1.pdf}}

\subsection{Relationships Between
Log-Returns}\label{relationships-between-log-returns}

\subsubsection{Covariance}\label{covariance}

Covariance measures how two variables change together:

\[
\text{Cov}(X, Y) = \frac{1}{n-1} \sum_{i=1}^{n} (X_i - \bar{X})(Y_i - \bar{Y})
\]

\begin{itemize}
\tightlist
\item
  \(X_i\), \(Y_i\) -- observations of variables X and Y\\
\item
  \(\bar{X}\), \(\bar{Y}\) -- arithmetic means of the variables\\
\item
  \(n\) -- number of observations
\end{itemize}

A positive covariance indicates that the log-returns of Alior and ING
tend to move together -- when one stock rises, the other usually rises
as well. A negative covariance would suggest that an increase in one
stock corresponds to a decrease in the other. A value close to zero
indicates little or no linear relationship. In the banking sector,
positive covariance is common, as stock prices often respond similarly
to macroeconomic factors and monetary policy.

\subsubsection{Correlation}\label{correlation}

Correlation normalizes covariance, resulting in a value between
\([-1,1]\), which makes it easier to assess the strength of the
relationship.

\paragraph{Pearson Correlation (P)}\label{pearson-correlation-p}

\[
r_P = \frac{\text{Cov}(X, Y)}{\sigma_X \sigma_Y}
\]

Pearson correlation measures the linear relationship between Alior and
ING log-returns. A value close to 1 means that changes in one stock's
log-returns are strongly associated with changes in the other in the
same direction. A value close to -1 indicates a strong inverse
relationship, and a value around 0 indicates little or no linear
correlation. In our case, \(r_P \approx 0.46\) shows a moderate positive
linear relationship, meaning the stocks often move in the same direction
but not perfectly in sync.

\paragraph{Spearman Correlation (S)}\label{spearman-correlation-s}

\[
r_S = 1 - \frac{6 \sum d_i^2}{n(n^2-1)}
\]

Spearman correlation is based on the ranks of observations and measures
monotonic relationships, without assuming linearity. A positive value
indicates that higher log-returns of one stock generally correspond to
higher log-returns of the other, even if the relationship is not
strictly linear. In practice, \(r_S \approx 0.43\) confirms a moderate
common trend in Alior and ING log-returns, consistent with expectations
for the banking sector.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cov}\NormalTok{(alior\_log\_returns, ing\_log\_returns)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0001352158
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(alior\_log\_returns, ing\_log\_returns, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4638365
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(alior\_log\_returns, ing\_log\_returns, }\AttributeTok{method =} \StringTok{"spearman"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4286084
\end{verbatim}

\subsection{Analysis of Log-Return Relationships Between Alior and
ING}\label{analysis-of-log-return-relationships-between-alior-and-ing}

Analyzing covariance and correlation allows us to assess the extent to
which the log-returns of two companies move together.

\begin{itemize}
\item
  \textbf{Positive covariance} indicates that Alior and ING log-returns
  tend to rise together. In other words, when one stock increases, the
  other generally also shows an upward movement.
\item
  \textbf{Pearson correlation (\(r \approx 0.46\))} shows a moderate
  positive linear relationship. This means that the stocks' log-returns
  generally tend to move in the same direction, although some scatter
  exists and the relationship is not perfectly linear.
\item
  \textbf{Spearman correlation (\(r \approx 0.43\))} measures monotonic
  association and indicates that higher ING log-returns are usually
  associated with higher Alior log-returns, even if the relationship is
  not exactly linear.
\end{itemize}

In summary, both linear and monotonic analyses confirm a moderate
positive dependence between Alior and ING log-returns, which is
consistent with expectations for companies in the same banking sector.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Linear Regression of Alior Log-Returns on
ING}\label{linear-regression-of-alior-log-returns-on-ing}

The purpose of linear regression is to create a model:

\[
Y = \beta_0 + \beta_1 X + \varepsilon
\]

\begin{itemize}
\tightlist
\item
  \(\beta_0\) -- intercept\\
\item
  \(\beta_1\) -- slope (coefficient)\\
\item
  \(\varepsilon\) -- random error
\end{itemize}

The model allows us to \textbf{describe the trend of the dependent
variable \(Y\) as a function of the independent variable \(X\)} and to
predict future values.

\subsubsection{\texorpdfstring{\(R^2\) (Coefficient of
Determination)}{R\^{}2 (Coefficient of Determination)}}\label{r2-coefficient-of-determination}

\[
R^2 = 1 - \frac{\sum (Y_i - \hat{Y}_i)^2}{\sum (Y_i - \bar{Y})^2}
\]

\begin{itemize}
\tightlist
\item
  \(\hat{Y}_i\) -- predicted values from the model\\
\item
  \(\bar{Y}\) -- mean of observed values
\end{itemize}

\textbf{Interpretation:} - \(R^2 \in [0,1]\)\\
- Explains the proportion of variance in the dependent variable that is
accounted for by the independent variable in the model\\
- Example: \(R^2 = 0.8\) means 80\% of the variance in \(Y\) is
explained by the linear model

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(alior\_log\_returns }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ing\_log\_returns)}
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = alior_log_returns ~ ing_log_returns)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.061428 -0.006672 -0.000796  0.006681  0.080233 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     0.0009562  0.0005943   1.609    0.108    
## ing_log_returns 0.5211673  0.0368928  14.127   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.01604 on 728 degrees of freedom
## Multiple R-squared:  0.2151, Adjusted R-squared:  0.2141 
## F-statistic: 199.6 on 1 and 728 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(ggExtra)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(alior\_ing, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ alior\_log\_returns, }\AttributeTok{y =}\NormalTok{ ing\_log\_returns)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.6}\NormalTok{, }\AttributeTok{color =} \StringTok{"darkblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Alior \& ING Bank Log{-}Returns (2023{-}2024) with Marginals"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Alior Bank"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"ING Bank"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}

\FunctionTok{ggMarginal}\NormalTok{(}
\NormalTok{  p,}
  \AttributeTok{type =} \StringTok{"histogram"}\NormalTok{,}
  \AttributeTok{margins =} \StringTok{"both"}\NormalTok{,}
  \AttributeTok{fill =} \StringTok{"lightblue"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{05_linear_regression_files/figure-latex/unnamed-chunk-9-1.pdf}}

Linear regression analysis allows us to assess to what extent the
variability of Alior log-returns can be explained by ING log-returns.

\begin{itemize}
\item
  \textbf{Intercept (0.0009562)} -- the average Alior log-return when
  ING log-return = 0. In practice, this means that if ING does not move,
  Alior also remains practically unchanged.
\item
  \textbf{Slope / coefficient for ING (0.5212)} -- indicates that, on
  average, each 1-unit increase in ING log-return is associated with a
  0.5212-unit increase in Alior log-return.
\item
  \textbf{\(R^2 = 0.2151\)} -- the model explains about 21.5\% of the
  variability in Alior log-returns based on ING. This represents a
  moderate level of fit, typical in finance where stock movements are
  largely random.
\item
  \(R^2 = 0.215\) also suggests that over 78\% of the variance in Alior
  log-returns is due to other factors, such as random market
  fluctuations, actions of other companies, or macroeconomic factors.
\end{itemize}

In summary, the linear regression confirms a statistical relationship
between the log-returns of the two companies, but it is not a strong
relationship. The \(R^2 = 0.215\) result is consistent with expectations
for financial data.

\end{document}
